clc;
foo = char(strsplit('SRL_OPRSSHA_2PTS008_0128_20131118_161158_20131118_175144.EUM.nc',{'_','.'}));

fam = foo(2,1);
typ = foo(2,3);
ver = foo(3,3);
dur = foo(3,4);
cyc = foo(3,5:end);
pas = foo(4,:);
frec = datetime(strjoin({foo(5,:), foo(6,:)}), ...
                'InputFormat','yyyyMMdd HHmmss');
lrec = datetime(strjoin({foo(7,:), foo(8,:)}), ...
                'InputFormat','yyyyMMdd HHmmss');
agn = foo(9,:);

tab = cell2table({fam, typ, ver, dur, cyc, pas, frec, lrec, agn}, ...
            'VariableNames', {'productFamily', ' productType', ... 
                              'productVersion', 'productDuration', ...
                              'cycleNumber', 'passNumber', ...
                              'firstProductRecord', 'lastProductRecord', ...
                              'Agency'});

